dist: trusty
sudo: required
language: python
python:
  - 2.7
  - 3.5
script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-environment
  - make test
cache:
  - apt
  - pip
install: ./provision.sh
